const express = require('express');
const cors = require('cors');
const { OpenAI } = require('openai');
require('dotenv').config();

const app = express();

// Enable CORS for frontend access
app.use(cors());

// Parse JSON request bodies
app.use(express.json());

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// API endpoint for AI explanations
app.post('/api/explain', async (req, res) => {
  try {
    const { question, options, correctAnswer, userAnswer } = req.body;

    // Validate required fields
    if (!question || !options || !correctAnswer) {
      return res.status(400).json({
        error: 'Missing required fields: question, options, and correctAnswer are required'
      });
    }

    // Check if API key is configured
    if (!process.env.OPENAI_API_KEY) {
      return res.status(500).json({
        error: 'OpenAI API key not configured on server'
      });
    }

    // Create prompt for OpenAI
    const prompt = `Question: ${question}
Options: ${options.join(', ')}
Correct Answer: ${correctAnswer}

Please provide a short explanation (under 150 words) of why the correct answer is right. Focus on the key facts and reasoning.`;

    // Call OpenAI API
    const response = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages: [
        {
          role: 'system',
          content: 'You are a helpful educational assistant. Provide clear, concise explanations for quiz answers. Keep explanations under 150 words and focus on why the answer is correct.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      max_tokens: 200,
      temperature: 0.7
    });

    const explanation = response.choices[0]?.message?.content?.trim();

    if (!explanation) {
      throw new Error('No explanation generated by OpenAI');
    }

    // Return the explanation
    res.json({ explanation });

  } catch (error) {
    console.error('Error generating explanation:', error);

    // Handle different types of errors
    if (error.response?.status === 401) {
      return res.status(500).json({
        error: 'Invalid OpenAI API key'
      });
    } else if (error.response?.status === 429) {
      return res.status(429).json({
        error: 'OpenAI API rate limit exceeded'
      });
    } else if (error.code === 'ECONNREFUSED' || error.message.includes('fetch')) {
      return res.status(503).json({
        error: 'Unable to connect to OpenAI API'
      });
    }

    // Generic error
    res.status(500).json({
      error: 'Failed to generate explanation. Please try again later.'
    });
  }
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'OK', timestamp: new Date().toISOString() });
});

// Start server
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Quiz backend server running on port ${PORT}`);
  console.log(`Health check: http://localhost:${PORT}/health`);
});